---
title: "Draft: Intro/Conclusions"
---

# Introduction

Power plants can face operational constraints due to environmental conditions. These constraints can lead to not being able to meet power demands as well as running at lower efficiency levels. One of the most impactful constraints is cooling. A way this has been mitigated is to have a connected system to help compensate for local constraints of plants. This solution has been adopted by the Alabama Power Company, which operates 81 generating units and 26 facilities @generati.

It is unknown how often a power plant will have to run at a reduced capacity as well as the reduction requirements, while still being able to meet demands. The objective of this report is to assess the risk that the Dauphin Island power plant will have to run at reduced capacity as well as the total impact. This study analyzes the frequency of months that exceed 85F and the generation at different reduced-capacity scenarios.

# Conclusion

This report analyzed the total impact of running at different levels of reduced capacity. We had found what time periods of the year we would likely need to run at reduced risk due to cooling restraints. The months that are at high risk, August and July, are months that will likely need to be run at reduced capacity of 10%. Months with moderate risk, June and September, are recommended to be prepared to operate at reduced capacity. There were no instances of temperature requiring reduced capacity of 20%. Despite reduced capacity during elevated temperatures, the power plant is sufficient to meet demands. Under a scenario where reduced capacity is impactful, it can be offset due to the Alabama Power Company's districts.

While the results indicate that reduced capacity is manageable under elevated temperatures and current demands, several limitations should be acknowledged and addressed for future analyses. A more extensive dataset would offset missing data and gather better trends based over years. Reproducing the power analysis for each of the given power plants would identify real contribution percentages for each power plant. Identifying trends in increasing demands to find if the impact increases.
