# Executive Summary

## Introduction {.unumbered}

Power plants are constrained to environmental factors. We must adapt to these constraints to maximize efficiency and avoid hazards. We focused on the James M. Barry Electric Generating Plant for this analysis.

## Methods {.unumbered}

We used historical temperature from the North Oceanic Atmospheric Administration and energy data from the U.S. Energy Information Administration. Monthly temperature averages and proportions of days exceeding 85°F were calculated by each month to define risk levels. Risk levels were defined as High being above 50% of the month having temperatures exceeding 85°F and moderate as being above 30%. Energy Generation was compared with Alabama Power Company's Energy consumption to identify impact of running at reduced capacity levels between 10% to 30%. We assossiated reduced capacity of 10% with temperature levels between 85°F and 95°F.

## Results {.unumbered}

The analysis showed seasonal increases in temperature during the months of April through October, with relevant risk from June through September. As shown in @fig-temp-time, July and August are identified as high risk, while **June (45.5%)** and **September (32%)** were identified as moderate risk. These months will approach or exceed critical thresholds over the next five years (@fig-rc-time). Energy generation remains sufficient across all evaluated reduced capacity scenarios. Under underperforming periods where we will not meet demands, the Alabama Power Company system can meet demand through load balancing.

## Conclusion {.unumbered}

The analysis indicates that reduced capacity is managable under current conditions. Despite summer months having increased risk, the power system is able to compensate to avoid negative impact. However, continued increase in temperature and demand can increase risks overtime. For future analyses we should incorporate additional data and broader system considerations.

::: callout-important
1.  The company should run at reduced efficiency during the moderate risk and high risk months (June - September).

2. To ensure security and adjust effectively, the company should conduct this analysis with information on the other power plants to be prepared for temperature rising.

3. Conduct this analysis every 5 years to identify changing trends
:::
