---
title: "Introduction"
---

Power plants can face operational constraints due to environmental conditions. These constraints can lead to plants being unable to meet demands and forcing decreased efficiency. One of the most impactful constraints is cooling because can cause emergency shutdown and equipment damage. A way this has been mitigated is by having a connected system to help compensate for local constraints of plants. This solution has been adopted by the Alabama Power Company, which operates 81 generating units and 26 facilities [@generati].

Despite this solution, there is still an uncertainty in how often you will have to run at reduced capacity for our Dauphin Island power plant. If we do not adjust for this, this can lead to component fatigue and shutdowns. In this report we asses the risk that the Dauphin Island power plant will have to run at reduced capacity. This study analyzes the frequency of months that exceed 85°F and the generation at different reduced-capacity scenarios. With running at reduced capacity because it can lead to failure to meet demand, we also analyze the capability the power plant is able to handle the demand. Demand is also projected for the next 5 years in order to identify increasing demand trends