---
title: "Methods"
---

## Water Temperature

We obtained a water temperature dataset[^methods-1] from the National Oceanic and Atmospheric Administration. The dataset had covered the hourly temperature observations from the years of 2002 to 2025 for the station in Dauphin Island [@station]. There were no available observations for the year of 2021, due to Hurricane Ida. This data was used to identify the likelihood of the water temperature exceeding the temperature before the plant would need to run at reduced capacity (\> 85°F) using a confidence interval of 95%. Monthly average temperatures and the proportion of days exceeding 85°F were calculated. Months were labeled depending on proportion of the month where temperature exceeds 85°F. Months that had over 50% of observations over 85°F was labeled as *high*. Months that were in between 50% and 20% were labeled as *moderate*.

[^methods-1]: <https://tidesandcurrents.noaa.gov/physocean.html?id=8735180>

## Power Requirements

We obtained a dataset[^methods-2] on consumption from the U.S. Energy Information Administration. The dataset includes the consumption sales, per month, from all power companies from the years of 2002 to 2025 [@formeia]. This dataset was used to find the consumption demands required by Alabama Power Company to meet demands (Megawatt hours).

[^methods-2]: <https://www.eia.gov/electricity/data/eia861m/>

We obtained a dataset[^methods-3] on generation from the U.S. Energy Information Administration. The dataset had covered net generation, per month, that the James M. Barry Electric Generating Plant from the years of 2002 to 2025 [@electric]. This dataset was used because Dauphin Island receives its power from the company Alabama Power Company, and this could be used to find the contribution a power plant would take [@alabama].

[^methods-3]: <https://www.eia.gov/beta/electricity/data/browser/#/plant/3?freq=M&start=202001&end=202512&ctype=linechart&ltype=pin&tab=generation&columnchart=ELEC.PLANT.GEN.3-ALL-ALL.M&maptype=0&pin=&linechart=>

This data was used to find the capabilities of the Dauphin Plant in the periods where we need to run at reduced capacity (Megawatt hours). We then compared this generation factored in with its contribution to consumption trends of Alabama Power Company. We defined reduced capacity as increments of 10%, so at the first increment the plant would be running at 90% efficiency. These would be applied once temperature exceeds the applicable amount, the thresholds were starting at 85°F and increases by 10°F. We used the capacity type *Normal Capacity* as the real capacity used at the date. We are applying the assumption that the power plant had not ran at reduced capcity to have a consistent approach of impact as we do not have data that confirms when the plant was running at reduced capacity.

James M. Barry Electric Generating Plant was chosen because it produces the most out of the power plants under Alabama Power Company, to compensate for a power plant needing to contribute proportionately we increased the contribution rate of the power plant [@generati].
